/**
 * Integration test — self-evolution engine end-to-end pipeline.
 *
 * Exercises the full flow WITHOUT the gateway:
 *   evaluate → generate → dedup → write → read → patch → lifecycle → preference → audit
 *
 * All I/O goes to a temp directory; no real LLM or Feishu API calls.
 */
import { describe, expect, it, beforeEach, afterEach } from "vitest";
import { mkdtempSync, rmSync, existsSync, readdirSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { EvolutionEngine } from "./engine.js";
import { EvolutionStore } from "./store.js";
import { SkillPersistenceWriter } from "./skill-writer.js";
import { SkillLifecycleManager } from "./skill-lifecycle.js";
import { EvolutionPreferenceAdapter } from "./preference-adapter.js";
import { AuditLog } from "./audit-log.js";
import { evaluateComplexity, detectTrialAndError } from "./complexity-evaluator.js";
import { generateSkillDraft } from "./skill-draft-generator.js";
import { generateSkillDraftLLM, buildPrompt, validateAndRepair } from "./llm-draft-generator.js";
import type {
  EvolutionCandidate,
  EvolutionRecord,
  SkillDraft,
  SkillPatch,
  ToolErrorProfile,
} from "./types.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

let tempDir: string;
let store: EvolutionStore;
let engine: EvolutionEngine;
let writer: SkillPersistenceWriter;
let lifecycle: SkillLifecycleManager;
let prefs: EvolutionPreferenceAdapter;
let audit: AuditLog;

function complexCandidate(overrides: Partial<EvolutionCandidate> = {}): EvolutionCandidate {
  return {
    taskSummary: "归档产品评审会议纪要到知识库并创建飞书任务",
    toolCalls: [
      "feishu_vc_search",
      "feishu_vc_notes",
      "feishu_doc_fetch",
      "feishu_wiki_spaces",
      "feishu_wiki_create",
      "feishu_doc_write",
      "feishu_task_create",
    ],
    uniqueToolCount: 6,
    reasoningTurns: 8,
    durationMs: 180_000,
    domain: "feishu-meeting",
    ...overrides,
  };
}

function simpleCandidate(): EvolutionCandidate {
  return {
    taskSummary: "查询天气",
    toolCalls: ["weather_get"],
    uniqueToolCount: 1,
    reasoningTurns: 1,
    durationMs: 2_000,
    domain: "weather",
  };
}

function trialErrorCandidate(): EvolutionCandidate {
  return complexCandidate({
    transcript: [
      "用户: 不对，不是这个文档",
      "Agent: 抱歉，我来重新查找",
      "用户: 换一种方式试试",
      "tool_call:feishu_doc_search",
      "tool_call:feishu_doc_search",
      "tool_call:feishu_doc_search",
      "Agent: 搞错了，让我重新来",
    ].join("\n"),
    hasTrialAndError: true,
    userCorrections: 2,
  });
}

function wellFormedSkillMd(name: string, description: string): string {
  return [
    "---",
    `name: ${name}`,
    `description: "${description}"`,
    "---",
    "",
    "## Triggers",
    "",
    `- ${name} 操作`,
    `- ${name} task`,
    `- 帮我${description}`,
    "",
    "## Workflow",
    "",
    "1. Do the first step.",
    "2. Do the second step.",
    "",
    "## Notes",
    "",
    "Auto-generated by self-evolution engine.",
  ].join("\n");
}

beforeEach(() => {
  tempDir = mkdtempSync(join(tmpdir(), "kaijibot-evo-pipeline-"));
  store = new EvolutionStore(tempDir);
  engine = new EvolutionEngine(store);
  writer = new SkillPersistenceWriter(tempDir);
  lifecycle = new SkillLifecycleManager(writer);
  prefs = new EvolutionPreferenceAdapter(tempDir);
  audit = new AuditLog(tempDir);
});

afterEach(() => {
  rmSync(tempDir, { recursive: true, force: true });
});

// ===========================================================================
// SCENARIO 1: Full happy-path — complex task → suggest → generate → save
// ===========================================================================
describe("Pipeline: happy path (complex task → skill saved)", () => {
  it("evaluates a complex task as suggestible", async () => {
    const candidate = complexCandidate();
    const decision = await engine.evaluate(candidate, "user-1");
    expect(decision.shouldSuggest).toBe(true);
    expect(decision.complexityScore).toBeGreaterThanOrEqual(0.6);
    expect(decision.reasoning).toContain("complex enough");
  });

  it("generates a draft and writes it to disk", async () => {
    const candidate = complexCandidate();
    const draft = await engine.generate(candidate);

    expect(draft.name).toBeTruthy();
    expect(draft.description).toBeTruthy();
    expect(draft.triggerPhrases.length).toBeGreaterThan(0);
    expect(draft.bodyMarkdown).toContain("## When to use");

    const savedPath = await writer.writeSkill(draft);
    expect(existsSync(savedPath)).toBe(true);

    const readBack = await writer.readSkill(draft.name);
    expect(readBack).not.toBeNull();
    expect(readBack!.name).toBe(draft.name);
  });

  it("end-to-end: evaluate → generate → dedup check → write → record", async () => {
    const candidate = complexCandidate();
    const userId = "user-e2e";

    // Step 1: Evaluate
    const decision = await engine.evaluate(candidate, userId);
    expect(decision.shouldSuggest).toBe(true);

    // Step 2: Check dedup (no existing skills → should create)
    const dedupResult = await engine.checkBeforeGenerate(candidate, lifecycle);
    expect(dedupResult.shouldCreate).toBe(true);

    // Step 3: Generate draft
    const draft = await engine.generate(candidate);

    // Step 4: Write to disk
    const savedPath = await writer.writeSkill(draft);
    expect(existsSync(savedPath)).toBe(true);

    // Step 5: Record the evolution
    const record: EvolutionRecord = {
      id: `rec-e2e-${Date.now()}`,
      userId,
      candidate,
      decision,
      draft,
      timestamp: Date.now(),
    };
    await store.save(record);

    // Step 6: Simulate user acceptance
    const updated = await engine.recordResponse(record.id, userId, "accepted", savedPath);
    expect(updated.userResponse).toBe("accepted");
    expect(updated.savedSkillPath).toBe(savedPath);

    // Step 7: Verify persistence
    const records = await store.list(userId);
    const found = records.find((r) => r.id === record.id);
    expect(found).toBeDefined();
    expect(found!.userResponse).toBe("accepted");

    // Step 8: Verify skill on disk has frontmatter
    const onDisk = await writer.readRawSkill(draft.name);
    expect(onDisk).not.toBeNull();
    expect(onDisk!.startsWith("---")).toBe(true);
  });
});

// ===========================================================================
// SCENARIO 2: Trial-and-error boost
// ===========================================================================
describe("Pipeline: trial-and-error detection boosts complexity", () => {
  it("detects Chinese correction signals in transcript", () => {
    const candidate = trialErrorCandidate();
    const result = detectTrialAndError(candidate);
    expect(result.detected).toBe(true);
    expect(result.signals.length).toBeGreaterThan(0);
    expect(result.boost).toBeGreaterThan(0);
  });

  it("trial-error candidate gets higher complexity than same candidate without", () => {
    const base = complexCandidate();
    const withTrial = trialErrorCandidate();

    const baseScore = evaluateComplexity(base).score;
    const trialScore = evaluateComplexity(withTrial).score;

    expect(trialScore).toBeGreaterThan(baseScore);
  });

  it("engine includes trial-error info in reasoning when suggesting", async () => {
    const candidate = trialErrorCandidate();
    const decision = await engine.evaluate(candidate, "user-trial");
    if (decision.shouldSuggest) {
      expect(decision.reasoning).toContain("Trial-and-error");
    }
  });

  it("transcript-only detection works (no hasTrialAndError flag)", () => {
    const candidate = complexCandidate({
      transcript: "用户: 不对，换一个\nAgent: 抱歉，让我重新来",
    });
    const result = detectTrialAndError(candidate);
    expect(result.detected).toBe(true);
  });

  it("no transcript and no flags → not detected", () => {
    const candidate = complexCandidate();
    const result = detectTrialAndError(candidate);
    expect(result.detected).toBe(false);
    expect(result.boost).toBe(0);
  });
});

// ===========================================================================
// SCENARIO 3: Recent suggestions context (no longer blocks)
// ===========================================================================
describe("Pipeline: recent suggestions as context", () => {
  it("provides recentSuggestions even after prior suggestions", async () => {
    const userId = "user-recent-ctx";

    const decision1 = await engine.evaluate(complexCandidate(), userId);
    expect(decision1.shouldSuggest).toBe(true);
    expect(decision1.recentSuggestions).toEqual([]);

    await store.save({
      id: "rec-recent",
      userId,
      candidate: complexCandidate(),
      decision: { shouldSuggest: true, confidence: 0.8, complexityScore: 0.7, reasoning: "test" },
      draft: { name: "test-skill", description: "d", triggerPhrases: ["t"], bodyMarkdown: "# T" },
      timestamp: Date.now() - 1000,
    });

    const decision2 = await engine.evaluate(complexCandidate(), userId);
    expect(decision2.shouldSuggest).toBe(true);
    expect(decision2.recentSuggestions).toHaveLength(1);
    expect(decision2.recentSuggestions![0].skillName).toBe("test-skill");
  });

  it("continues suggesting regardless of prior suggestion count", async () => {
    const userId = "user-no-block";

    for (let i = 0; i < 5; i++) {
      await store.save({
        id: `rec-many-${i}`,
        userId,
        candidate: complexCandidate(),
        decision: { shouldSuggest: true, confidence: 0.8, complexityScore: 0.7, reasoning: "fill" },
        draft: { name: `skill-${i}`, description: "d", triggerPhrases: ["t"], bodyMarkdown: "# T" },
        timestamp: Date.now() - 1000,
      });
    }

    const decision = await engine.evaluate(complexCandidate(), userId);
    expect(decision.shouldSuggest).toBe(true);
    expect(decision.recentSuggestions).toHaveLength(5);
  });
});

// ===========================================================================
// SCENARIO 4: Dedup — similar skill exists → suggest patch instead
// ===========================================================================
describe("Pipeline: dedup prevents duplicate skills", () => {
  it("blocks creation when similar skill exists", async () => {
    // Pre-create a similar skill
    await writer.writeSkill({
      name: "feishu-meeting",
      description: "归档产品评审会议纪要到知识库并创建飞书任务",
      triggerPhrases: ["会议归档"],
      bodyMarkdown: "# Meeting Archive\n\nHandles meeting archiving.",
    });

    const candidate = complexCandidate();
    const result = await engine.checkBeforeGenerate(candidate, lifecycle);

    expect(result.shouldCreate).toBe(false);
    expect(result.existingSkill).toBe("feishu-meeting");
  });

  it("allows creation when domain is different", async () => {
    await writer.writeSkill({
      name: "weather-forecast",
      description: "Get weather forecasts for cities",
      triggerPhrases: ["天气"],
      bodyMarkdown: "# Weather",
    });

    const candidate = complexCandidate();
    const result = await engine.checkBeforeGenerate(candidate, lifecycle);

    expect(result.shouldCreate).toBe(true);
  });

  it("allows creation when no lifecycle manager provided", async () => {
    const candidate = complexCandidate();
    const result = await engine.checkBeforeGenerate(candidate);
    expect(result.shouldCreate).toBe(true);
  });
});

// ===========================================================================
// SCENARIO 5: Skill patch — text replacement and LLM paths
// ===========================================================================
describe("Pipeline: skill patching", () => {
  it("fast-path: direct text replacement without LLM", async () => {
    await writer.writeSkill({
      name: "test-patch",
      description: "Test skill for patching",
      triggerPhrases: ["test"],
      bodyMarkdown: "## Old Section\n\nOld content here.",
    });

    const patch: SkillPatch = {
      name: "test-patch",
      instructions: "Update the section",
      replacements: [{ oldText: "Old content here.", newText: "New content here." }],
    };

    const result = await engine.patchSkill(patch, { writer });

    expect(result.ok).toBe(true);
    if (result.ok) {
      const raw = await writer.readRawSkill("test-patch");
      expect(raw).toContain("New content here.");
      expect(raw).not.toContain("Old content here.");
    }
  });

  it("returns error when old text not found", async () => {
    await writer.writeSkill({
      name: "test-missing",
      description: "Test",
      triggerPhrases: [],
      bodyMarkdown: "Hello world",
    });

    const result = await engine.patchSkill(
      { name: "test-missing", instructions: "fix", replacements: [{ oldText: "DOES_NOT_EXIST", newText: "x" }] },
      { writer },
    );

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).toContain("not found");
    }
  });

  it("LLM path: uses generateText to update skill", async () => {
    await writer.writeSkill({
      name: "test-llm-patch",
      description: "Original",
      triggerPhrases: ["trigger"],
      bodyMarkdown: "## Old",
    });

    const newContent = wellFormedSkillMd("test-llm-patch", "Updated by LLM");
    const mockLlm = async () => newContent;

    const result = await engine.patchSkill(
      { name: "test-llm-patch", instructions: "Rewrite everything" },
      { generateText: mockLlm, writer },
    );

    expect(result.ok).toBe(true);
    if (result.ok) {
      const raw = await writer.readRawSkill("test-llm-patch");
      expect(raw).toContain("Updated by LLM");
    }
  });

  it("returns error when skill does not exist", async () => {
    const result = await engine.patchSkill(
      { name: "ghost-skill", instructions: "update" },
      { generateText: async () => "", writer },
    );
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).toContain("Skill not found");
    }
  });

  it("LLM failure returns error", async () => {
    await writer.writeSkill({
      name: "test-llm-fail",
      description: "Test",
      triggerPhrases: [],
      bodyMarkdown: "Body",
    });

    const failingLlm = async () => { throw new Error("API timeout"); };

    const result = await engine.patchSkill(
      { name: "test-llm-fail", instructions: "Update" },
      { generateText: failingLlm, writer },
    );

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).toContain("Failed to patch");
    }
  });

  it("no replacements and no LLM → error", async () => {
    await writer.writeSkill({
      name: "test-no-llm",
      description: "Test",
      triggerPhrases: [],
      bodyMarkdown: "Body",
    });

    const result = await engine.patchSkill(
      { name: "test-no-llm", instructions: "Change something" },
      { writer },
    );

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).toContain("LLM text generation required");
    }
  });
});

// ===========================================================================
// SCENARIO 6: Lifecycle — usage tracking, staleness, expiry
// ===========================================================================
describe("Pipeline: skill lifecycle management", () => {
  it("tracks usage via touchSkill", async () => {
    await writer.writeSkill({
      name: "lifecycle-test",
      description: "Test lifecycle",
      triggerPhrases: ["test"],
      bodyMarkdown: "Body",
    });

    const meta0 = await writer.readSkillMeta("lifecycle-test");
    expect(meta0).not.toBeNull();
    expect(meta0!.usageCount).toBe(0);

    await writer.touchSkill("lifecycle-test");
    const meta1 = await writer.readSkillMeta("lifecycle-test");
    expect(meta1!.usageCount).toBe(1);

    await writer.touchSkill("lifecycle-test");
    const meta2 = await writer.readSkillMeta("lifecycle-test");
    expect(meta2!.usageCount).toBe(2);
    expect(meta2!.lastUsedAt).toBeGreaterThan(0);
  });

  it("detects stale skills", async () => {
    const staleCandidate: EvolutionCandidate = {
      taskSummary: "old task",
      toolCalls: ["tool"],
      uniqueToolCount: 1,
      reasoningTurns: 1,
      durationMs: 1000,
      domain: "old",
    };
    const draft = generateSkillDraft(staleCandidate);

    // Write with normal creation
    await writer.writeSkill(draft);

    // Force lastUsedAt to 31 days ago
    const raw = await writer.readRawSkill(draft.name);
    expect(raw).not.toBeNull();
    const staleTimestamp = Date.now() - 31 * 86400000;
    const patched = raw!.replace(
      /lastUsedAt:\s*\d+/,
      `lastUsedAt: ${staleTimestamp}`,
    );
    await writer.updateSkill(draft.name, patched);

    const meta = await writer.readSkillMeta(draft.name);
    expect(meta).not.toBeNull();
    expect(meta!.isStale).toBe(true);
  });

  it("removes stale skills with zero usage", async () => {
    // Create two skills: one stale+unused, one recent
    await writer.writeSkill({
      name: "stale-skill",
      description: "Old skill",
      triggerPhrases: ["old"],
      bodyMarkdown: "Old",
    });
    await writer.writeSkill({
      name: "fresh-skill",
      description: "Fresh skill",
      triggerPhrases: ["new"],
      bodyMarkdown: "Fresh",
    });

    // Force stale-skill to be old and unused
    const raw = await writer.readRawSkill("stale-skill");
    const staleTs = Date.now() - 31 * 86400000;
    const patched = raw!.replace(/lastUsedAt:\s*\d+/, `lastUsedAt: ${staleTs}`).replace(/usageCount:\s*\d+/, "usageCount: 0");
    await writer.updateSkill("stale-skill", patched);

    const removed = await lifecycle.removeStale(30);
    expect(removed).toBe(1);

    expect(await writer.skillExists("stale-skill")).toBe(false);
    expect(await writer.skillExists("fresh-skill")).toBe(true);
  });

  it("does NOT remove stale skills that have been used", async () => {
    await writer.writeSkill({
      name: "used-but-stale",
      description: "Used but old",
      triggerPhrases: [],
      bodyMarkdown: "Body",
    });

    // Make stale but with usageCount > 0
    const raw = await writer.readRawSkill("used-but-stale");
    const staleTs = Date.now() - 31 * 86400000;
    const patched = raw!
      .replace(/lastUsedAt:\s*\d+/, `lastUsedAt: ${staleTs}`)
      .replace(/usageCount:\s*\d+/, "usageCount: 5");
    await writer.updateSkill("used-but-stale", patched);

    const removed = await lifecycle.removeStale(30);
    expect(removed).toBe(0);
    expect(await writer.skillExists("used-but-stale")).toBe(true);
  });
});

// ===========================================================================
// SCENARIO 7: Preference learning — Thompson Sampling
// ===========================================================================
describe("Pipeline: preference learning (Thompson Sampling)", () => {
  it("starts with prior for unseen domain", async () => {
    const rate = await prefs.getDomainAcceptanceRate("user-1", "unknown-domain");
    // Prior alpha=2, beta=1 → expected ~0.667, but sampled so just check range
    expect(rate).toBeGreaterThan(0);
    expect(rate).toBeLessThanOrEqual(1);
  });

  it("increases acceptance rate after accepted responses", async () => {
    const userId = "user-pref";
    const domain = "feishu-meeting";

    // Record several acceptances
    for (let i = 0; i < 5; i++) {
      await prefs.recordResponse(userId, domain, "accepted");
    }

    const bandit = await prefs.getRawBandit(userId, domain);
    expect(bandit).toBeDefined();
    expect(bandit!.alpha).toBeGreaterThan(2); // prior + accepts
    expect(bandit!.beta).toBe(1); // prior unchanged

    // Sample should tend high
    const samples: number[] = [];
    for (let i = 0; i < 100; i++) {
      samples.push(await prefs.getDomainAcceptanceRate(userId, domain));
    }
    const avg = samples.reduce((a, b) => a + b, 0) / samples.length;
    expect(avg).toBeGreaterThan(0.7);
  });

  it("decreases acceptance rate after rejected responses", async () => {
    const userId = "user-reject";
    const domain = "weather";

    for (let i = 0; i < 5; i++) {
      await prefs.recordResponse(userId, domain, "rejected");
    }

    const bandit = await prefs.getRawBandit(userId, domain);
    expect(bandit!.beta).toBeGreaterThan(1);

    const samples: number[] = [];
    for (let i = 0; i < 100; i++) {
      samples.push(await prefs.getDomainAcceptanceRate(userId, domain));
    }
    const avg = samples.reduce((a, b) => a + b, 0) / samples.length;
    expect(avg).toBeLessThan(0.5);
  });

  it("modified response gives half-credit", async () => {
    const userId = "user-mod";
    const domain = "code-review";

    await prefs.recordResponse(userId, domain, "modified");

    const bandit = await prefs.getRawBandit(userId, domain);
    expect(bandit!.alpha).toBe(2.5); // prior(2) + 0.5
  });

  it("engine uses preference adapter to adjust confidence", async () => {
    const userId = "user-conf";
    const domain = "feishu-meeting";

    // Boost acceptance rate
    for (let i = 0; i < 10; i++) {
      await prefs.recordResponse(userId, domain, "accepted");
    }

    const engineWithPrefs = new EvolutionEngine(store, undefined, prefs);
    const candidate = complexCandidate({ domain });

    const decision = await engineWithPrefs.evaluate(candidate, userId);
    expect(decision.shouldSuggest).toBe(true);
    // Confidence should be adjusted by domain acceptance rate
    // With many accepts, confidence should be close to complexityScore
    expect(decision.confidence).toBeGreaterThan(0);
  });
});

// ===========================================================================
// SCENARIO 8: Audit log — records all operations
// ===========================================================================
describe("Pipeline: audit logging", () => {
  it("appends entries and queries them back", async () => {
    await audit.append({
      operation: "skill_suggest",
      actor: "user-1",
      target: "feishu-meeting-archive",
      outcome: "success",
    });

    await audit.append({
      operation: "skill_accept",
      actor: "user-1",
      target: "feishu-meeting-archive",
      outcome: "success",
    });

    const all = await audit.query({ actor: "user-1" });
    expect(all.length).toBe(2);

    const suggests = await audit.query({ operation: "skill_suggest" });
    expect(suggests.length).toBe(1);
    expect(suggests[0].operation).toBe("skill_suggest");
  });

  it("filters by timestamp", async () => {
    const now = Date.now();

    await audit.append({
      operation: "old_op",
      actor: "user-1",
      target: "x",
      outcome: "success",
    });

    // Wait to ensure different timestamp
    await new Promise((r) => setTimeout(r, 5));

    await audit.append({
      operation: "new_op",
      actor: "user-1",
      target: "y",
      outcome: "success",
    });

    const recent = await audit.query({ since: Date.now() - 2 });
    expect(recent.length).toBe(1);
    expect(recent[0].operation).toBe("new_op");
  });

  it("returns empty for no matches", async () => {
    const results = await audit.query({ actor: "nobody" });
    expect(results).toEqual([]);
  });
});

// ===========================================================================
// SCENARIO 9: LLM draft generator — prompt construction and validation
// ===========================================================================
describe("Pipeline: LLM draft generation", () => {
  it("builds a prompt containing skill-creator spec and candidate info", () => {
    const candidate = complexCandidate();
    const prompt = buildPrompt(candidate);

    expect(prompt).toContain("Task to Analyze");
    expect(prompt).toContain(candidate.taskSummary);
    expect(prompt).toContain(candidate.domain);
    expect(prompt).toContain("SKILL.md");
  });

  it("validates and returns draft from well-formed LLM output", async () => {
    const candidate = complexCandidate();
    const llmOutput = wellFormedSkillMd("test-llm-draft", "LLM generated skill for testing");

    const draft = validateAndRepair(llmOutput, candidate);
    expect(draft.name).toBe("test-llm-draft");
    expect(draft.description).toBeTruthy();
    expect(draft.triggerPhrases.length).toBeGreaterThan(0);
  });

  it("falls back to rule-based draft when LLM output is malformed", async () => {
    const candidate = complexCandidate();
    const draft = validateAndRepair("garbage output without frontmatter", candidate);

    // Should fall back to generateSkillDraft
    expect(draft.name).toBeTruthy();
    expect(draft.description).toBeTruthy();
  });

  it("handles markdown code fence wrapping", async () => {
    const candidate = complexCandidate();
    const content = wellFormedSkillMd("fenced-skill", "Fenced skill");
    const wrapped = "```markdown\n" + content + "\n```";

    const draft = validateAndRepair(wrapped, candidate);
    expect(draft.name).toBe("fenced-skill");
  });

  it("falls back when Triggers section is missing", async () => {
    const candidate = complexCandidate();
    const noTriggers = "---\nname: no-triggers\ndescription: \"No triggers\"\n---\n\n## Workflow\n\n1. Step one.";

    const draft = validateAndRepair(noTriggers, candidate);
    // Falls back to rule-based because no trigger phrases extracted
    expect(draft.name).toBeTruthy();
  });

  it("full generateSkillDraftLLM with mock LLM", async () => {
    const candidate = complexCandidate();
    const goodOutput = wellFormedSkillMd("llm-full-test", "Full LLM generation test");

    const draft = await generateSkillDraftLLM(candidate, {
      generateText: async () => goodOutput,
    });

    expect(draft.name).toBe("llm-full-test");
    expect(draft.triggerPhrases.length).toBeGreaterThan(0);
  });

  it("falls back to rule-based when LLM throws", async () => {
    const candidate = complexCandidate();

    const draft = await generateSkillDraftLLM(candidate, {
      generateText: async () => { throw new Error("LLM unavailable"); },
    });

    // Should still produce a draft via fallback
    expect(draft.name).toBeTruthy();
    expect(draft.description).toBeTruthy();
  });
});

// ===========================================================================
// SCENARIO 10: Writer edge cases — path safety, atomicity, list
// ===========================================================================
describe("Pipeline: skill writer edge cases", () => {
  it("rejects path traversal in skill name", async () => {
    await expect(writer.writeSkill({
      name: "../etc/passwd",
      description: "Evil",
      triggerPhrases: [],
      bodyMarkdown: "Bad",
    })).rejects.toThrow("Invalid skill name");
  });

  it("rejects absolute path in skill name", async () => {
    await expect(writer.writeSkill({
      name: "/tmp/evil",
      description: "Evil",
      triggerPhrases: [],
      bodyMarkdown: "Bad",
    })).rejects.toThrow("Invalid skill name");
  });

  it("rejects backslash in skill name", async () => {
    await expect(writer.writeSkill({
      name: "evil\\skill",
      description: "Evil",
      triggerPhrases: [],
      bodyMarkdown: "Bad",
    })).rejects.toThrow("Invalid skill name");
  });

  it("listSkillNames returns only valid skill directories", async () => {
    await writer.writeSkill({ name: "skill-a", description: "A", triggerPhrases: [], bodyMarkdown: "A" });
    await writer.writeSkill({ name: "skill-b", description: "B", triggerPhrases: [], bodyMarkdown: "B" });

    const names = await writer.listSkillNames();
    expect(names.sort()).toEqual(["skill-a", "skill-b"]);
  });

  it("readSkill returns null for nonexistent skill", async () => {
    const result = await writer.readSkill("does-not-exist");
    expect(result).toBeNull();
  });

  it("readRawSkill returns null for nonexistent skill", async () => {
    const result = await writer.readRawSkill("does-not-exist");
    expect(result).toBeNull();
  });

  it("removeSkill deletes the skill directory", async () => {
    await writer.writeSkill({ name: "to-remove", description: "X", triggerPhrases: [], bodyMarkdown: "X" });
    expect(await writer.skillExists("to-remove")).toBe(true);

    await writer.removeSkill("to-remove");
    expect(await writer.skillExists("to-remove")).toBe(false);
  });

  it("updateSkill overwrites content atomically", async () => {
    await writer.writeSkill({ name: "update-test", description: "Original", triggerPhrases: [], bodyMarkdown: "Original" });

    const newPath = await writer.updateSkill("update-test", "Updated content");
    expect(existsSync(newPath)).toBe(true);

    const raw = await writer.readRawSkill("update-test");
    expect(raw).toBe("Updated content");
  });

  it("updateSkill throws for nonexistent skill", async () => {
    await expect(writer.updateSkill("ghost", "content")).rejects.toThrow("Skill not found");
  });
});

// ===========================================================================
// SCENARIO 11: Config persistence
// ===========================================================================
describe("Pipeline: config persistence", () => {
  it("saves and loads config", async () => {
    await store.saveConfig({ ...await store.loadConfig(), minComplexity: 0.8 });

    const loaded = await store.loadConfig();
    expect(loaded.minComplexity).toBe(0.8);
  });

  it("returns defaults when no config file exists", async () => {
    const config = await store.loadConfig();
    expect(config.minComplexity).toBe(0.4);
    expect(config.enabled).toBe(true);
  });
});

// ===========================================================================
// SCENARIO 12: Multi-user isolation
// ===========================================================================
describe("Pipeline: multi-user isolation", () => {
  it("different users have separate records and preferences", async () => {
    const userA = "user-a";
    const userB = "user-b";

    // User A: accept feishu-meeting
    await prefs.recordResponse(userA, "feishu-meeting", "accepted");
    // User B: reject feishu-meeting multiple times
    await prefs.recordResponse(userB, "feishu-meeting", "rejected");
    await prefs.recordResponse(userB, "feishu-meeting", "rejected");

    const banditA = await prefs.getRawBandit(userA, "feishu-meeting");
    const banditB = await prefs.getRawBandit(userB, "feishu-meeting");

    expect(banditA!.alpha).toBeGreaterThan(banditA!.beta);
    expect(banditB!.beta).toBeGreaterThan(banditB!.alpha);

    // Different records
    const recordA: EvolutionRecord = {
      id: "rec-a",
      userId: userA,
      candidate: complexCandidate(),
      decision: { shouldSuggest: true, confidence: 0.8, complexityScore: 0.7, reasoning: "test" },
      timestamp: Date.now(),
    };
    await store.save(recordA);

    const aRecords = await store.list(userA);
    const bRecords = await store.list(userB);

    expect(aRecords.length).toBe(1);
    expect(bRecords.length).toBe(0);
  });
});

// ===========================================================================
// SCENARIO 13: Store atomic writes (no partial data on crash)
// ===========================================================================
describe("Pipeline: store reliability", () => {
  it("save → list round-trips correctly", async () => {
    const record: EvolutionRecord = {
      id: "rec-rt",
      userId: "user-rt",
      candidate: complexCandidate(),
      decision: { shouldSuggest: true, confidence: 0.9, complexityScore: 0.8, reasoning: "round-trip" },
      timestamp: Date.now(),
    };

    await store.save(record);
    const loaded = await store.list("user-rt");

    expect(loaded.length).toBe(1);
    expect(loaded[0].id).toBe("rec-rt");
    expect(loaded[0].candidate.taskSummary).toBe(record.candidate.taskSummary);
  });

  it("getRecentSuggestions filters by time and shouldSuggest", async () => {
    const userId = "user-recent";

    // Old suggestion (25h ago)
    await store.save({
      id: "rec-old",
      userId,
      candidate: simpleCandidate(),
      decision: { shouldSuggest: true, confidence: 0.5, complexityScore: 0.5, reasoning: "old" },
      timestamp: Date.now() - 25 * 3600000,
    });

    // Recent suggestion (1h ago)
    await store.save({
      id: "rec-new",
      userId,
      candidate: complexCandidate(),
      decision: { shouldSuggest: true, confidence: 0.8, complexityScore: 0.7, reasoning: "new" },
      timestamp: Date.now() - 3600000,
    });

    // Non-suggestion (should not appear)
    await store.save({
      id: "rec-nosuggest",
      userId,
      candidate: complexCandidate(),
      decision: { shouldSuggest: false, confidence: 0, complexityScore: 0.3, reasoning: "no" },
      timestamp: Date.now() - 1000,
    });

    const recent = await store.getRecentSuggestions(userId, 24);
    expect(recent.length).toBe(1);
    expect(recent[0].id).toBe("rec-new");
  });
});

// ===========================================================================
// SCENARIO 14: Full rejection flow — user rejects, preference adapts
// ===========================================================================
describe("Pipeline: rejection → preference adaptation", () => {
  it("user rejects → preference adapts → future confidence drops", async () => {
    const userId = "user-reject-flow";
    const domain = "feishu-meeting";

    // Engine with preference adapter
    const engineWithPrefs = new EvolutionEngine(store, undefined, prefs);

    // First: evaluate and suggest
    const decision1 = await engineWithPrefs.evaluate(complexCandidate({ domain }), userId);
    expect(decision1.shouldSuggest).toBe(true);
    const baseConfidence = decision1.confidence;

    // User rejects
    await prefs.recordResponse(userId, domain, "rejected");

    // Now acceptance rate should be lower
    const rate = await prefs.getDomainAcceptanceRate(userId, domain);
    // With 1 rejection: beta goes from 1→2, alpha stays 2
    // Expected value = 2/(2+2) = 0.5, but it's sampled so just check it decreased on average
    const samples: number[] = [];
    for (let i = 0; i < 200; i++) {
      samples.push(await prefs.getDomainAcceptanceRate(userId, domain));
    }
    const avgRate = samples.reduce((a, b) => a + b, 0) / samples.length;
    expect(avgRate).toBeLessThan(0.7); // Prior was ~0.667, should be lower now
  });
});

// ===========================================================================
// SCENARIO 15: Disabled engine
// ===========================================================================
describe("Pipeline: disabled engine", () => {
  it("never suggests when disabled", async () => {
    const disabledEngine = new EvolutionEngine(store, { enabled: false });
    const decision = await disabledEngine.evaluate(complexCandidate(), "user-disabled");
    expect(decision.shouldSuggest).toBe(false);
    expect(decision.reasoning).toContain("disabled");
  });
});

// ===========================================================================
// SCENARIO 16: Concurrent writes — two skills written simultaneously
// ===========================================================================
describe("Pipeline: concurrent operations", () => {
  it("writes two skills concurrently without corruption", async () => {
    const draft1: SkillDraft = {
      name: "concurrent-a",
      description: "Skill A",
      triggerPhrases: ["a"],
      bodyMarkdown: "# A",
    };
    const draft2: SkillDraft = {
      name: "concurrent-b",
      description: "Skill B",
      triggerPhrases: ["b"],
      bodyMarkdown: "# B",
    };

    const [path1, path2] = await Promise.all([
      writer.writeSkill(draft1),
      writer.writeSkill(draft2),
    ]);

    expect(existsSync(path1)).toBe(true);
    expect(existsSync(path2)).toBe(true);

    const r1 = await writer.readRawSkill("concurrent-a");
    const r2 = await writer.readRawSkill("concurrent-b");

    expect(r1).toContain("# A");
    expect(r2).toContain("# B");
  });
});

// ===========================================================================
// SCENARIO 17: LLM draft generator full flow with custom draft generator
// ===========================================================================
describe("Pipeline: custom draft generator injection", () => {
  it("engine uses injected draft generator over default", async () => {
    const customDraft: SkillDraft = {
      name: "custom-skill",
      description: "Custom generated",
      triggerPhrases: ["custom"],
      bodyMarkdown: "# Custom\n\nThis is custom.",
    };

    const customGenerator = async () => customDraft;
    const engineWithCustom = new EvolutionEngine(store, undefined, undefined, customGenerator);

    const result = await engineWithCustom.generate(complexCandidate());
    expect(result.name).toBe("custom-skill");
    expect(result.bodyMarkdown).toContain("Custom");
  });
});

// ===========================================================================
// SCENARIO 18: Error-prone simple task triggers evolution (errorComplexityThreshold)
// ===========================================================================
describe("Pipeline: error-driven evolution for simple tasks", () => {
  it("simple task with tool errors triggers suggestion", async () => {
    const candidate = simpleCandidate();
    candidate.errorProfile = {
      errorCount: 2,
      failedToolNames: ["weather_get"],
      hasMutatingErrors: false,
    };
    const decision = await engine.evaluate(candidate, "user-err-simple");
    expect(decision.shouldSuggest).toBe(true);
    expect(decision.reasoning).toContain("error threshold");
  });

  it("retries without errors do NOT trigger error threshold", async () => {
    const candidate: EvolutionCandidate = {
      taskSummary: "查询天气（重试了3次）",
      toolCalls: ["weather_get", "weather_get", "weather_get", "weather_get"],
      uniqueToolCount: 1,
      reasoningTurns: 4,
      durationMs: 15_000,
      domain: "weather",
    };
    const decision = await engine.evaluate(candidate, "user-retry-simple");
    expect(decision.shouldSuggest).toBe(false);
  });

  it("simple task without errors does NOT trigger (backward compat)", async () => {
    const candidate = simpleCandidate();
    const decision = await engine.evaluate(candidate, "user-clean-simple");
    expect(decision.shouldSuggest).toBe(false);
  });
});

// ===========================================================================
// SCENARIO 19: Error-prone simple task gets higher priority than smooth complex task
// ===========================================================================
describe("Pipeline: error priority vs smooth complexity", () => {
  it("error-based suggestion includes error info in reasoning", async () => {
    const candidate: EvolutionCandidate = {
      taskSummary: "创建飞书文档",
      toolCalls: ["feishu_doc_create", "feishu_doc_create", "feishu_doc_create"],
      uniqueToolCount: 1,
      reasoningTurns: 3,
      durationMs: 10_000,
      domain: "feishu-doc",
      errorProfile: {
        errorCount: 2,
        failedToolNames: ["feishu_doc_create"],
        hasMutatingErrors: true,
      },
    };
    const decision = await engine.evaluate(candidate, "user-err-priority");
    expect(decision.shouldSuggest).toBe(true);
    expect(decision.reasoning).toContain("Tool errors detected");
    expect(decision.reasoning).toContain("feishu_doc_create");
  });

  it("smooth complex task still uses minComplexity threshold", async () => {
    const candidate = complexCandidate();
    const decision = await engine.evaluate(candidate, "user-smooth-complex");
    expect(decision.shouldSuggest).toBe(true);
    expect(decision.reasoning).not.toContain("error threshold");
    expect(decision.reasoning).toContain("complex enough");
  });
});

// ===========================================================================
// SCENARIO 20: Error-driven trigger provides context
// ===========================================================================
describe("Pipeline: error-driven trigger provides recent context", () => {
  it("error-based suggestion includes recentSuggestions context", async () => {
    const userId = "user-err-ctx";

    const recentRecord: EvolutionRecord = {
      id: "rec-err-recent",
      userId,
      candidate: simpleCandidate(),
      decision: { shouldSuggest: true, confidence: 0.5, complexityScore: 0.4, reasoning: "err" },
      draft: { name: "prev-skill", description: "d", triggerPhrases: ["t"], bodyMarkdown: "# T" },
      timestamp: Date.now() - 1000,
    };
    await store.save(recentRecord);

    const candidate = simpleCandidate();
    candidate.errorProfile = {
      errorCount: 3,
      failedToolNames: ["weather_get"],
      hasMutatingErrors: false,
    };
    const decision = await engine.evaluate(candidate, userId);
    expect(decision.shouldSuggest).toBe(true);
    expect(decision.recentSuggestions).toHaveLength(1);
    expect(decision.recentSuggestions![0].skillName).toBe("prev-skill");
  });
});

// ===========================================================================
// SCENARIO 21: Backward compatibility — existing tests still pass
// ===========================================================================
describe("Pipeline: backward compatibility with error fields", () => {
  it("complex candidate without errorProfile still works", async () => {
    const candidate = complexCandidate();
    expect(candidate.errorProfile).toBeUndefined();
    const decision = await engine.evaluate(candidate, "user-backward");
    expect(decision.shouldSuggest).toBe(true);
  });

  it("complex candidate with empty errorProfile uses minComplexity", async () => {
    const candidate = complexCandidate();
    candidate.errorProfile = { errorCount: 0, failedToolNames: [], hasMutatingErrors: false };
    const decision = await engine.evaluate(candidate, "user-zero-err");
    expect(decision.shouldSuggest).toBe(true);
  });

  it("trial-and-error + error profile both contribute", async () => {
    const candidate = trialErrorCandidate();
    candidate.errorProfile = {
      errorCount: 1,
      failedToolNames: ["feishu_doc_search"],
      hasMutatingErrors: false,
    };
    const decision = await engine.evaluate(candidate, "user-combined");
    expect(decision.shouldSuggest).toBe(true);
    expect(decision.reasoning).toContain("Trial-and-error");
    expect(decision.reasoning).toContain("Tool errors detected");
  });
});
