import { mkdtempSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
/**
 * Integration test — self-evolution engine end-to-end pipeline.
 *
 * Exercises the remaining engine flow (generate → dedup → write → read → patch → lifecycle → audit)
 * WITHOUT the gateway. All I/O goes to a temp directory; no real LLM or Feishu API calls.
 */
import { describe, expect, it, beforeEach, afterEach } from "vitest";
import { AuditLog } from "./audit-log.js";
import { EvolutionEngine } from "./engine.js";
import { generateSkillDraftLLM, buildPrompt, validateAndRepair } from "./llm-draft-generator.js";
import { generateSkillDraft } from "./skill-draft-generator.js";
import { SkillLifecycleManager } from "./skill-lifecycle.js";
import { SkillPersistenceWriter } from "./skill-writer.js";
import { EvolutionStore } from "./store.js";
import type { EvolutionCandidate, EvolutionRecord, SkillDraft, SkillPatch } from "./types.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

let tempDir: string;
let store: EvolutionStore;
let engine: EvolutionEngine;
let writer: SkillPersistenceWriter;
let lifecycle: SkillLifecycleManager;
let audit: AuditLog;
const AGENT = "main";

function complexCandidate(overrides: Partial<EvolutionCandidate> = {}): EvolutionCandidate {
  return {
    taskSummary: "归档产品评审会议纪要到知识库并创建飞书任务",
    toolCalls: [
      "feishu_vc_search",
      "feishu_vc_notes",
      "feishu_doc_fetch",
      "feishu_wiki_spaces",
      "feishu_wiki_create",
      "feishu_doc_write",
      "feishu_task_create",
    ],
    uniqueToolCount: 6,
    reasoningTurns: 8,
    durationMs: 180_000,
    domain: "feishu-meeting",
    ...overrides,
  };
}

function wellFormedSkillMd(name: string, description: string): string {
  return [
    "---",
    `name: ${name}`,
    `description: "${description}"`,
    "---",
    "",
    "## Triggers",
    "",
    `- ${name} 操作`,
    `- ${name} task`,
    `- 帮我${description}`,
    "",
    "## Workflow",
    "",
    "1. Do the first step.",
    "2. Do the second step.",
    "",
    "## Notes",
    "",
    "Auto-generated by self-evolution engine.",
  ].join("\n");
}

beforeEach(() => {
  tempDir = mkdtempSync(join(tmpdir(), "kaijibot-evo-pipeline-"));
  store = new EvolutionStore(tempDir);
  engine = new EvolutionEngine(store);
  writer = new SkillPersistenceWriter(tempDir);
  lifecycle = new SkillLifecycleManager(writer);
  audit = new AuditLog(tempDir);
});

afterEach(() => {
  rmSync(tempDir, { recursive: true, force: true });
});

// ===========================================================================
// SCENARIO 1: Generate a draft and write it to disk
// ===========================================================================
describe("Pipeline: draft generation and persistence", () => {
  it("generates a draft and writes it to disk", async () => {
    const candidate = complexCandidate();
    const draft = await engine.generate(candidate);

    expect(draft.name).toBeTruthy();
    expect(draft.description).toBeTruthy();
    expect(draft.triggerPhrases.length).toBeGreaterThan(0);
    expect(draft.bodyMarkdown).toContain("## When to use");

    const savedPath = await writer.writeSkill(draft);
    expect(existsSync(savedPath)).toBe(true);

    const readBack = await writer.readSkill(draft.name);
    expect(readBack).not.toBeNull();
    expect(readBack!.name).toBe(draft.name);
  });
});

// ===========================================================================
// SCENARIO 2: Dedup — similar skill exists → suggest patch instead
// ===========================================================================
describe("Pipeline: dedup prevents duplicate skills", () => {
  it("blocks creation when similar skill exists", async () => {
    // Pre-create a similar skill
    await writer.writeSkill({
      name: "feishu-meeting",
      description: "归档产品评审会议纪要到知识库并创建飞书任务",
      triggerPhrases: ["会议归档"],
      bodyMarkdown: "# Meeting Archive\n\nHandles meeting archiving.",
    });

    const candidate = complexCandidate();
    const result = await engine.checkBeforeGenerate(candidate, lifecycle);

    expect(result.shouldCreate).toBe(false);
    expect(result.existingSkill).toBe("feishu-meeting");
  });

  it("allows creation when domain is different", async () => {
    await writer.writeSkill({
      name: "weather-forecast",
      description: "Get weather forecasts for cities",
      triggerPhrases: ["天气"],
      bodyMarkdown: "# Weather",
    });

    const candidate = complexCandidate();
    const result = await engine.checkBeforeGenerate(candidate, lifecycle);

    expect(result.shouldCreate).toBe(true);
  });

  it("allows creation when no lifecycle manager provided", async () => {
    const candidate = complexCandidate();
    const result = await engine.checkBeforeGenerate(candidate);
    expect(result.shouldCreate).toBe(true);
  });
});

// ===========================================================================
// SCENARIO 3: Skill patch — text replacement and LLM paths
// ===========================================================================
describe("Pipeline: skill patching", () => {
  it("fast-path: direct text replacement without LLM", async () => {
    await writer.writeSkill({
      name: "test-patch",
      description: "Test skill for patching",
      triggerPhrases: ["test"],
      bodyMarkdown: "## Old Section\n\nOld content here.",
    });

    const patch: SkillPatch = {
      name: "test-patch",
      instructions: "Update the section",
      replacements: [{ oldText: "Old content here.", newText: "New content here." }],
    };

    const result = await engine.patchSkill(patch, { writer });

    expect(result.ok).toBe(true);
    if (result.ok) {
      const raw = await writer.readRawSkill("test-patch");
      expect(raw).toContain("New content here.");
      expect(raw).not.toContain("Old content here.");
    }
  });

  it("returns error when old text not found", async () => {
    await writer.writeSkill({
      name: "test-missing",
      description: "Test",
      triggerPhrases: [],
      bodyMarkdown: "Hello world",
    });

    const result = await engine.patchSkill(
      {
        name: "test-missing",
        instructions: "fix",
        replacements: [{ oldText: "DOES_NOT_EXIST", newText: "x" }],
      },
      { writer },
    );

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).toContain("not found");
    }
  });

  it("LLM path: uses generateText to update skill", async () => {
    await writer.writeSkill({
      name: "test-llm-patch",
      description: "Original",
      triggerPhrases: ["trigger"],
      bodyMarkdown: "## Old",
    });

    const newContent = wellFormedSkillMd("test-llm-patch", "Updated by LLM");
    const mockLlm = async () => newContent;

    const result = await engine.patchSkill(
      { name: "test-llm-patch", instructions: "Rewrite everything" },
      { generateText: mockLlm, writer },
    );

    expect(result.ok).toBe(true);
    if (result.ok) {
      const raw = await writer.readRawSkill("test-llm-patch");
      expect(raw).toContain("Updated by LLM");
    }
  });

  it("returns error when skill does not exist", async () => {
    const result = await engine.patchSkill(
      { name: "ghost-skill", instructions: "update" },
      { generateText: async () => "", writer },
    );
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).toContain("Skill not found");
    }
  });

  it("LLM failure returns error", async () => {
    await writer.writeSkill({
      name: "test-llm-fail",
      description: "Test",
      triggerPhrases: [],
      bodyMarkdown: "Body",
    });

    const failingLlm = async () => {
      throw new Error("API timeout");
    };

    const result = await engine.patchSkill(
      { name: "test-llm-fail", instructions: "Update" },
      { generateText: failingLlm, writer },
    );

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).toContain("Failed to patch");
    }
  });

  it("no replacements and no LLM → error", async () => {
    await writer.writeSkill({
      name: "test-no-llm",
      description: "Test",
      triggerPhrases: [],
      bodyMarkdown: "Body",
    });

    const result = await engine.patchSkill(
      { name: "test-no-llm", instructions: "Change something" },
      { writer },
    );

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).toContain("LLM text generation required");
    }
  });
});

// ===========================================================================
// SCENARIO 4: Lifecycle — usage tracking, staleness, expiry
// ===========================================================================
describe("Pipeline: skill lifecycle management", () => {
  it("tracks usage via touchSkill", async () => {
    await writer.writeSkill({
      name: "lifecycle-test",
      description: "Test lifecycle",
      triggerPhrases: ["test"],
      bodyMarkdown: "Body",
    });

    const meta0 = await writer.readSkillMeta("lifecycle-test");
    expect(meta0).not.toBeNull();
    expect(meta0!.usageCount).toBe(0);

    await writer.touchSkill("lifecycle-test");
    const meta1 = await writer.readSkillMeta("lifecycle-test");
    expect(meta1!.usageCount).toBe(1);

    await writer.touchSkill("lifecycle-test");
    const meta2 = await writer.readSkillMeta("lifecycle-test");
    expect(meta2!.usageCount).toBe(2);
    expect(meta2!.lastUsedAt).toBeGreaterThan(0);
  });

  it("detects stale skills", async () => {
    const staleCandidate: EvolutionCandidate = {
      taskSummary: "old task",
      toolCalls: ["tool"],
      uniqueToolCount: 1,
      reasoningTurns: 1,
      durationMs: 1000,
      domain: "old",
    };
    const draft = generateSkillDraft(staleCandidate);

    // Write with normal creation
    await writer.writeSkill(draft);

    // Force lastUsedAt to 31 days ago
    const raw = await writer.readRawSkill(draft.name);
    expect(raw).not.toBeNull();
    const staleTimestamp = Date.now() - 31 * 86400000;
    const patched = raw!.replace(/lastUsedAt:\s*\d+/, `lastUsedAt: ${staleTimestamp}`);
    await writer.updateSkill(draft.name, patched);

    const meta = await writer.readSkillMeta(draft.name);
    expect(meta).not.toBeNull();
    expect(meta!.isStale).toBe(true);
  });

  it("removes stale skills with zero usage", async () => {
    // Create two skills: one stale+unused, one recent
    await writer.writeSkill({
      name: "stale-skill",
      description: "Old skill",
      triggerPhrases: ["old"],
      bodyMarkdown: "Old",
    });
    await writer.writeSkill({
      name: "fresh-skill",
      description: "Fresh skill",
      triggerPhrases: ["new"],
      bodyMarkdown: "Fresh",
    });

    // Force stale-skill to be old and unused
    const raw = await writer.readRawSkill("stale-skill");
    const staleTs = Date.now() - 31 * 86400000;
    const patched = raw!
      .replace(/lastUsedAt:\s*\d+/, `lastUsedAt: ${staleTs}`)
      .replace(/usageCount:\s*\d+/, "usageCount: 0");
    await writer.updateSkill("stale-skill", patched);

    const removed = await lifecycle.removeStale(30);
    expect(removed).toBe(1);

    expect(await writer.skillExists("stale-skill")).toBe(false);
    expect(await writer.skillExists("fresh-skill")).toBe(true);
  });

  it("does NOT remove stale skills that have been used", async () => {
    await writer.writeSkill({
      name: "used-but-stale",
      description: "Used but old",
      triggerPhrases: [],
      bodyMarkdown: "Body",
    });

    // Make stale but with usageCount > 0
    const raw = await writer.readRawSkill("used-but-stale");
    const staleTs = Date.now() - 31 * 86400000;
    const patched = raw!
      .replace(/lastUsedAt:\s*\d+/, `lastUsedAt: ${staleTs}`)
      .replace(/usageCount:\s*\d+/, "usageCount: 5");
    await writer.updateSkill("used-but-stale", patched);

    const removed = await lifecycle.removeStale(30);
    expect(removed).toBe(0);
    expect(await writer.skillExists("used-but-stale")).toBe(true);
  });
});

// ===========================================================================
// SCENARIO 5: Audit log — records all operations
// ===========================================================================
describe("Pipeline: audit logging", () => {
  it("appends entries and queries them back", async () => {
    await audit.append({
      operation: "skill_suggest",
      actor: "user-1",
      target: "feishu-meeting-archive",
      outcome: "success",
    });

    await audit.append({
      operation: "skill_accept",
      actor: "user-1",
      target: "feishu-meeting-archive",
      outcome: "success",
    });

    const all = await audit.query({ actor: "user-1" });
    expect(all.length).toBe(2);

    const suggests = await audit.query({ operation: "skill_suggest" });
    expect(suggests.length).toBe(1);
    expect(suggests[0].operation).toBe("skill_suggest");
  });

  it("filters by timestamp", async () => {
    await audit.append({
      operation: "old_op",
      actor: "user-1",
      target: "x",
      outcome: "success",
    });

    // Wait to ensure different timestamp
    await new Promise((r) => setTimeout(r, 5));

    await audit.append({
      operation: "new_op",
      actor: "user-1",
      target: "y",
      outcome: "success",
    });

    const recent = await audit.query({ since: Date.now() - 2 });
    expect(recent.length).toBe(1);
    expect(recent[0].operation).toBe("new_op");
  });

  it("returns empty for no matches", async () => {
    const results = await audit.query({ actor: "nobody" });
    expect(results).toEqual([]);
  });
});

// ===========================================================================
// SCENARIO 6: LLM draft generator — prompt construction and validation
// ===========================================================================
describe("Pipeline: LLM draft generation", () => {
  it("builds a prompt containing skill-creator spec and candidate info", () => {
    const candidate = complexCandidate();
    const prompt = buildPrompt(candidate);

    expect(prompt).toContain("Task to Analyze");
    expect(prompt).toContain(candidate.taskSummary);
    expect(prompt).toContain(candidate.domain);
    expect(prompt).toContain("SKILL.md");
  });

  it("validates and returns draft from well-formed LLM output", async () => {
    const candidate = complexCandidate();
    const llmOutput = wellFormedSkillMd("test-llm-draft", "LLM generated skill for testing");

    const draft = validateAndRepair(llmOutput, candidate);
    expect(draft.name).toBe("test-llm-draft");
    expect(draft.description).toBeTruthy();
    expect(draft.triggerPhrases.length).toBeGreaterThan(0);
  });

  it("falls back to rule-based draft when LLM output is malformed", async () => {
    const candidate = complexCandidate();
    const draft = validateAndRepair("garbage output without frontmatter", candidate);

    // Should fall back to generateSkillDraft
    expect(draft.name).toBeTruthy();
    expect(draft.description).toBeTruthy();
  });

  it("handles markdown code fence wrapping", async () => {
    const candidate = complexCandidate();
    const content = wellFormedSkillMd("fenced-skill", "Fenced skill");
    const wrapped = "```markdown\n" + content + "\n```";

    const draft = validateAndRepair(wrapped, candidate);
    expect(draft.name).toBe("fenced-skill");
  });

  it("falls back when Triggers section is missing", async () => {
    const candidate = complexCandidate();
    const noTriggers =
      '---\nname: no-triggers\ndescription: "No triggers"\n---\n\n## Workflow\n\n1. Step one.';

    const draft = validateAndRepair(noTriggers, candidate);
    // Falls back to rule-based because no trigger phrases extracted
    expect(draft.name).toBeTruthy();
  });

  it("full generateSkillDraftLLM with mock LLM", async () => {
    const candidate = complexCandidate();
    const goodOutput = wellFormedSkillMd("llm-full-test", "Full LLM generation test");

    const draft = await generateSkillDraftLLM(candidate, {
      generateText: async () => goodOutput,
    });

    expect(draft.name).toBe("llm-full-test");
    expect(draft.triggerPhrases.length).toBeGreaterThan(0);
  });

  it("falls back to rule-based when LLM throws", async () => {
    const candidate = complexCandidate();

    const draft = await generateSkillDraftLLM(candidate, {
      generateText: async () => {
        throw new Error("LLM unavailable");
      },
    });

    // Should still produce a draft via fallback
    expect(draft.name).toBeTruthy();
    expect(draft.description).toBeTruthy();
  });
});

// ===========================================================================
// SCENARIO 7: Writer edge cases — path safety, atomicity, list
// ===========================================================================
describe("Pipeline: skill writer edge cases", () => {
  it("rejects path traversal in skill name", async () => {
    await expect(
      writer.writeSkill({
        name: "../etc/passwd",
        description: "Evil",
        triggerPhrases: [],
        bodyMarkdown: "Bad",
      }),
    ).rejects.toThrow("Invalid skill name");
  });

  it("rejects absolute path in skill name", async () => {
    await expect(
      writer.writeSkill({
        name: "/tmp/evil",
        description: "Evil",
        triggerPhrases: [],
        bodyMarkdown: "Bad",
      }),
    ).rejects.toThrow("Invalid skill name");
  });

  it("rejects backslash in skill name", async () => {
    await expect(
      writer.writeSkill({
        name: "evil\\skill",
        description: "Evil",
        triggerPhrases: [],
        bodyMarkdown: "Bad",
      }),
    ).rejects.toThrow("Invalid skill name");
  });

  it("listSkillNames returns only valid skill directories", async () => {
    await writer.writeSkill({
      name: "skill-a",
      description: "A",
      triggerPhrases: [],
      bodyMarkdown: "A",
    });
    await writer.writeSkill({
      name: "skill-b",
      description: "B",
      triggerPhrases: [],
      bodyMarkdown: "B",
    });

    const names = await writer.listSkillNames();
    expect(names.toSorted()).toEqual(["skill-a", "skill-b"]);
  });

  it("readSkill returns null for nonexistent skill", async () => {
    const result = await writer.readSkill("does-not-exist");
    expect(result).toBeNull();
  });

  it("readRawSkill returns null for nonexistent skill", async () => {
    const result = await writer.readRawSkill("does-not-exist");
    expect(result).toBeNull();
  });

  it("removeSkill deletes the skill directory", async () => {
    await writer.writeSkill({
      name: "to-remove",
      description: "X",
      triggerPhrases: [],
      bodyMarkdown: "X",
    });
    expect(await writer.skillExists("to-remove")).toBe(true);

    await writer.removeSkill("to-remove");
    expect(await writer.skillExists("to-remove")).toBe(false);
  });

  it("updateSkill overwrites content atomically", async () => {
    await writer.writeSkill({
      name: "update-test",
      description: "Original",
      triggerPhrases: [],
      bodyMarkdown: "Original",
    });

    const newPath = await writer.updateSkill("update-test", "Updated content");
    expect(existsSync(newPath)).toBe(true);

    const raw = await writer.readRawSkill("update-test");
    expect(raw).toBe("Updated content");
  });

  it("updateSkill throws for nonexistent skill", async () => {
    await expect(writer.updateSkill("ghost", "content")).rejects.toThrow("Skill not found");
  });
});

// ===========================================================================
// SCENARIO 8: Config persistence
// ===========================================================================
describe("Pipeline: config persistence", () => {
  it("saves and loads config", async () => {
    await store.saveConfig(AGENT, { ...(await store.loadConfig(AGENT)), enabled: false });

    const loaded = await store.loadConfig(AGENT);
    expect(loaded.enabled).toBe(false);
  });

  it("returns defaults when no config file exists", async () => {
    const config = await store.loadConfig(AGENT);
    expect(config.enabled).toBe(true);
  });
});

// ===========================================================================
// SCENARIO 9: Store atomic writes (no partial data on crash)
// ===========================================================================
describe("Pipeline: store reliability", () => {
  it("save → list round-trips correctly", async () => {
    const record: EvolutionRecord = {
      id: "rec-rt",
      userId: "user-rt",
      candidate: complexCandidate(),
      draft: {
        name: "round-trip-skill",
        description: "d",
        triggerPhrases: ["t"],
        bodyMarkdown: "# RT",
      },
      timestamp: Date.now(),
    };

    await store.save(AGENT, record);
    const loaded = await store.list(AGENT, "user-rt");

    expect(loaded.length).toBe(1);
    expect(loaded[0].id).toBe("rec-rt");
    expect(loaded[0].candidate.taskSummary).toBe(record.candidate.taskSummary);
  });

  it("getRecentSuggestions filters by time and presence of draft", async () => {
    const userId = "user-recent";

    // Old suggestion (25h ago)
    await store.save(AGENT, {
      id: "rec-old",
      userId,
      candidate: complexCandidate(),
      draft: { name: "old-skill", description: "d", triggerPhrases: ["t"], bodyMarkdown: "# O" },
      timestamp: Date.now() - 25 * 3600000,
    });

    // Recent suggestion (1h ago)
    await store.save(AGENT, {
      id: "rec-new",
      userId,
      candidate: complexCandidate(),
      draft: { name: "new-skill", description: "d", triggerPhrases: ["t"], bodyMarkdown: "# N" },
      timestamp: Date.now() - 3600000,
    });

    // Non-suggestion (no draft — should not appear)
    await store.save(AGENT, {
      id: "rec-nosuggest",
      userId,
      candidate: complexCandidate(),
      timestamp: Date.now() - 1000,
    });

    const recent = await store.getRecentSuggestions(AGENT, userId, 24);
    expect(recent.length).toBe(1);
    expect(recent[0].id).toBe("rec-new");
  });
});

// ===========================================================================
// SCENARIO 10: Concurrent writes — two skills written simultaneously
// ===========================================================================
describe("Pipeline: concurrent operations", () => {
  it("writes two skills concurrently without corruption", async () => {
    const draft1: SkillDraft = {
      name: "concurrent-a",
      description: "Skill A",
      triggerPhrases: ["a"],
      bodyMarkdown: "# A",
    };
    const draft2: SkillDraft = {
      name: "concurrent-b",
      description: "Skill B",
      triggerPhrases: ["b"],
      bodyMarkdown: "# B",
    };

    const [path1, path2] = await Promise.all([
      writer.writeSkill(draft1),
      writer.writeSkill(draft2),
    ]);

    expect(existsSync(path1)).toBe(true);
    expect(existsSync(path2)).toBe(true);

    const r1 = await writer.readRawSkill("concurrent-a");
    const r2 = await writer.readRawSkill("concurrent-b");

    expect(r1).toContain("# A");
    expect(r2).toContain("# B");
  });
});

// ===========================================================================
// SCENARIO 11: Custom draft generator injection
// ===========================================================================
describe("Pipeline: custom draft generator injection", () => {
  it("engine uses injected draft generator over default", async () => {
    const customDraft: SkillDraft = {
      name: "custom-skill",
      description: "Custom generated",
      triggerPhrases: ["custom"],
      bodyMarkdown: "# Custom\n\nThis is custom.",
    };

    const customGenerator = async () => customDraft;
    const engineWithCustom = new EvolutionEngine(store, customGenerator);

    const result = await engineWithCustom.generate(complexCandidate());
    expect(result.name).toBe("custom-skill");
    expect(result.bodyMarkdown).toContain("Custom");
  });
});
