import type { EvolutionCandidate, SkillDraft } from "./types.js";

export function toKebabCase(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-");
}

export function sanitizeSkillName(name: string): string {
  return toKebabCase(name).replace(/^-+|-+$/g, "");
}

function generateName(candidate: EvolutionCandidate): string {
  const domain = sanitizeSkillName(candidate.domain);
  if (candidate.toolCalls.length === 0) return `${domain}-workflow`;
  const primaryTool = sanitizeSkillName(candidate.toolCalls[0]);
  return `${domain}-${primaryTool}`;
}

const MAX_DESCRIPTION_LENGTH = 200;

function generateDescription(candidate: EvolutionCandidate): string {
  const raw = `${candidate.taskSummary}. Use when user needs similar ${candidate.domain} operations.`;
  if (raw.length <= MAX_DESCRIPTION_LENGTH) return raw;
  return raw.slice(0, MAX_DESCRIPTION_LENGTH - 1) + "…";
}

function generateTriggerPhrases(candidate: EvolutionCandidate): string[] {
  const phrases: string[] = [];
  const domain = candidate.domain;
  const tools = candidate.toolCalls;

  if (tools.length > 0) {
    phrases.push(`${tools[0]} 操作`);
    phrases.push(`${tools[0]} task`);
  }

  phrases.push(`${domain} 流程`);
  phrases.push(`${domain} workflow`);
  phrases.push(`${domain} operations`);

  return phrases.slice(0, 5);
}

function deduplicate<T>(items: T[]): T[] {
  const seen = new Set<T>();
  const result: T[] = [];
  for (const item of items) {
    if (!seen.has(item)) {
      seen.add(item);
      result.push(item);
    }
  }
  return result;
}

function generateBodyMarkdown(candidate: EvolutionCandidate): string {
  const lines: string[] = [];

  lines.push("## When to use");
  lines.push("");
  lines.push(
    `Use when the user requests ${candidate.domain} operations similar to: ${candidate.taskSummary}.`,
  );
  lines.push("");

  lines.push("## Workflow");
  lines.push("");
  const uniqueTools = deduplicate(candidate.toolCalls);
  if (uniqueTools.length === 0) {
    lines.push("1. Follow the standard workflow for the task.");
  } else {
    uniqueTools.forEach((tool, i) => {
      lines.push(`${i + 1}. Use \`${tool}\` to accomplish the relevant sub-task.`);
    });
  }
  lines.push("");

  lines.push("## Notes");
  lines.push("");
  lines.push(
    "This skill was auto-generated by the self-evolution engine. Review and verify before relying on it.",
  );
  lines.push("");

  return lines.join("\n");
}

export function generateSkillDraft(candidate: EvolutionCandidate): SkillDraft {
  return {
    name: generateName(candidate),
    description: generateDescription(candidate),
    triggerPhrases: generateTriggerPhrases(candidate),
    bodyMarkdown: generateBodyMarkdown(candidate),
  };
}
