import type { InsightRecord } from "../types.js";

export type InsightMode = "surprise" | "extend";

/** Inferred search strategy produced by the interest inference layer. */
export type SearchStrategy = {
  /** Latent interest or knowledge gap identified in the user. */
  inferredInterest: string;
  /** English search query for web search. */
  searchQuery: string;
  /** Why this connects to the user's latent interests. */
  bridgeReasoning: string;
  /** Topics already well-covered (to avoid re-treading). */
  avoidTopics: string[];
  /** Estimated surprise value 0-1. */
  estimatedSurprise: number;
};

export type InferenceResult =
  | { ok: true; strategy: SearchStrategy }
  | { ok: false; error: string };

/** Input to the insight engine */
export type InsightEngineInput = {
  /** User's active domains of interest */
  targetDomains: string[];
  /** User's recent focus areas */
  recentFocus: string[];
  /** User's trust score */
  trustScore: number;
  /** Recent insights already delivered (to avoid duplicates) */
  recentInsightIds: string[];
  /** Recent insight text contents (for anti-repetition contrastive prompting) */
  recentInsightContents: string[];
  /** Insight generation mode — determines prompt frame and search strategy. */
  mode?: InsightMode;
};

/** Candidate insight generated by the engine */
export type InsightCandidate = {
  id: string;
  content: string;
  rationale: string;
  targetDomains: string[];
  sourceDomains: string[];
  relevanceScore: number;
  surpriseScore: number;
  compositeScore: number;
  sources: Array<{ url: string; title: string; credibility: number }>;
  verificationStatus: "unverified" | "partial" | "verified" | "contradicted";
};

/** Verification result from the pipeline */
export type VerificationResult = {
  status: "unverified" | "partial" | "verified" | "contradicted";
  sources: Array<{ url: string; title: string; credibility: number }>;
  confidence: number;
  notes?: string;
};
