import type { FeedbackProfile } from "../types.js";
import type { Fragment, FragmentCluster } from "./fragment-types.js";
import type { InsightRecord } from "../types.js";

export type PromptBuildResult = {
  prompt: string;
  variant: {
    fewShotSet: number;
    frameIndex: number;
    structureSeed?: number;
    patternFrame?: number;
  };
};

export type InsightMode = "surprise" | "extend" | "pattern";

/** Inferred search strategy produced by the interest inference layer. */
export type SearchStrategy = {
  /** Latent interest or knowledge gap identified in the user. */
  inferredInterest: string;
  /** English search query for web search. */
  searchQuery: string;
  /** Why this connects to the user's latent interests. */
  bridgeReasoning: string;
  /** Topics already well-covered (to avoid re-treading). */
  avoidTopics: string[];
  /** Estimated surprise value 0-1. */
  estimatedSurprise: number;
};

export type InferenceResult =
  | { ok: true; strategy: SearchStrategy }
  | { ok: false; error: string };

/** Input to the insight engine */
export type InsightEngineInput = {
  /** User's active domains of interest */
  targetDomains: string[];
  /** User's recent focus areas */
  recentFocus: string[];
  /** User's trust score */
  trustScore: number;
  /** Recent insights already delivered (to avoid duplicates) */
  recentInsightIds: string[];
  /** Recent insight text contents (for anti-repetition contrastive prompting) */
  recentInsightContents: string[];
  /** Insight generation mode — determines prompt frame and search strategy. */
  mode?: InsightMode;
  /** Last 10 search queries used — used to diversify the next query. */
  recentQueryHistory?: string[];
  /** Domain combinations recently covered — LLM must AVOID these. */
  recentInsightDomains?: string[][];
  /** Fragment clusters for pattern-mode insights (populated by unified generator). */
  fragmentClusters?: FragmentCluster[];
  /** Individual fragments for pattern-mode prompt enrichment. */
  fragments?: Fragment[];
  /** Feedback profile for Thompson Sampling prompt variant selection. */
  feedbackProfile?: FeedbackProfile;
};

/** Candidate insight generated by the engine */
export type InsightCandidate = {
  id: string;
  content: string;
  rationale: string;
  targetDomains: string[];
  sourceDomains: string[];
  relevanceScore: number;
  surpriseScore: number;
  compositeScore: number;
  sources: Array<{ url: string; title: string; credibility: number }>;
  verificationStatus: "unverified" | "partial" | "verified" | "contradicted";
  source?: "v1" | "v2";
  searchQueryUsed?: string;
  promptVariant?: InsightRecord["promptVariant"];
};

/** Result of LLM-based critique of an insight candidate. */
export type LlmCritiqueResult = {
  specificity: number;
  personaRelevance: number;
  actionability: number;
  surprise: number;
  voiceMatch: number;
  overallScore: number;
  critique: string;
  improvementSuggestions: string[];
};

/** Verification result from the pipeline */
export type VerificationResult = {
  status: "unverified" | "partial" | "verified" | "contradicted";
  sources: Array<{ url: string; title: string; credibility: number }>;
  confidence: number;
  notes?: string;
};
