import type { InsightRecord } from "../types.js";

/** Input to the insight engine */
export type InsightEngineInput = {
  /** User's active domains of interest */
  targetDomains: string[];
  /** User's recent focus areas */
  recentFocus: string[];
  /** User's pending questions */
  pendingQuestions: string[];
  /** User's trust score */
  trustScore: number;
  /** Recent insights already delivered (to avoid duplicates) */
  recentInsightIds: string[];
  /** Recent insight text contents (for anti-repetition contrastive prompting) */
  recentInsightContents: string[];
};

/** Candidate insight generated by the engine */
export type InsightCandidate = {
  id: string;
  content: string;
  rationale: string;
  targetDomains: string[];
  sourceDomains: string[];
  relevanceScore: number;
  surpriseScore: number;
  compositeScore: number;
  sources: Array<{ url: string; title: string; credibility: number }>;
  verificationStatus: "unverified" | "partial" | "verified" | "contradicted";
};

/** Verification result from the pipeline */
export type VerificationResult = {
  status: "unverified" | "partial" | "verified" | "contradicted";
  sources: Array<{ url: string; title: string; credibility: number }>;
  confidence: number;
  notes?: string;
};
