export const browserCoreExamples = [
  "kaijibot browser status",
  "kaijibot browser start",
  "kaijibot browser stop",
  "kaijibot browser tabs",
  "kaijibot browser open https://example.com",
  "kaijibot browser focus abcd1234",
  "kaijibot browser close abcd1234",
  "kaijibot browser screenshot",
  "kaijibot browser screenshot --full-page",
  "kaijibot browser screenshot --ref 12",
  "kaijibot browser snapshot",
  "kaijibot browser snapshot --format aria --limit 200",
  "kaijibot browser snapshot --efficient",
  "kaijibot browser snapshot --labels",
];

export const browserActionExamples = [
  "kaijibot browser navigate https://example.com",
  "kaijibot browser resize 1280 720",
  "kaijibot browser click 12 --double",
  'kaijibot browser type 23 "hello" --submit',
  "kaijibot browser press Enter",
  "kaijibot browser hover 44",
  "kaijibot browser drag 10 11",
  "kaijibot browser select 9 OptionA OptionB",
  "kaijibot browser upload /tmp/kaijibot/uploads/file.pdf",
  'kaijibot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "kaijibot browser dialog --accept",
  'kaijibot browser wait --text "Done"',
  "kaijibot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "kaijibot browser console --level error",
  "kaijibot browser pdf",
];
